pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t cloud-native-devops-app:${BUILD_NUMBER} -f docker/Dockerfile .'
               }
            }
        stage('AWS Auth Test') {
            steps {
             withCredentials([usernamePassword(
             credentialsId: 'aws-ecr-credentials',
             usernameVariable: 'AWS_ACCESS_KEY_ID',
             passwordVariable: 'AWS_SECRET_ACCESS_KEY'
            )]) {
            sh 'aws sts get-caller-identity --region us-east-1'
                } 
               }
             }
        }
}
